### ISSUE TITLE
Auto remove of the tmp files from the tmp files

### ISSUE THREAD

**Issue by m-diers** [Delgan/qml-format#8] opened 2024-12-02 09:32 UTC
In my case, tmp versions of the tmp files were always left behind (with a ~ at the end). No idea why.

I have adjusted the routine once so that the files are not left behind:

```js
const runExternalFormatter = async (command, args, fileContent, filePath, tmpExtension) => {
    const randomString = Math.random().toString(36).substring(2, 10);
    const pathObject = path.parse(filePath);
    const fileName = pathObject.base;
    const tempFilePath = path.join(pathObject.dir, `${pathObject.name}-${randomString}-formatting-tmp.${tmpExtension}`);

    const deleteFilesMatchingPattern = (pattern) => {
        return new Promise((resolve) => {
            fs.readdir(pathObject.dir, (err, files) => {
                if (err) {
                    console.error(`Failed to read directory for cleanup: ${err.message}`);
                    return resolve();
                }
                const filesToDelete = files.filter((file) => file.match(pattern));
                let deleteCount = 0;
                filesToDelete.forEach((file) => {
                    const fullPath = path.join(pathObject.dir, file);
                    fs.unlink(fullPath, (unlinkErr) => {
                        if (unlinkErr) {
                            console.error(`Failed to delete file '${fullPath}': ${unlinkErr.message}`);
                        }
                        deleteCount++;
                        if (deleteCount === filesToDelete.length) {
                            resolve();
                        }
                    });
                });
                if (filesToDelete.length === 0) resolve();
            });
        });
    };

    if (!fileContent.trim()) {
        return "";
    }

    try {
        await new Promise((resolve, reject) => {
            fs.access(tempFilePath, fs.constants.F_OK, (err) => {
                if (!err) {
                    return reject(new Error(`File '${tempFilePath}' already exists.`));
                }
                resolve();
            });
        });

        await new Promise((resolve, reject) => {
            fs.writeFile(tempFilePath, fileContent, (err) => {
                if (err) {
                    return reject(new Error(`Could not create temporary file: ${err.message}`));
                }
                resolve();
            });
        });

        await new Promise((resolve, reject) => {
            child_process.execFile(command, ["-i", tempFilePath].concat(args), (err, stdout, stderr) => {
                if (err) {
                    return reject(new Error(`Formatting failed: ${err.message}`));
                }
                resolve();
            });
        });

        const formattedContent = await new Promise((resolve, reject) => {
            fs.readFile(tempFilePath, (err, data) => {
                if (err) {
                    return reject(new Error(`Could not read temporary file: ${err.message}`));
                }
                resolve(data.toString("utf8"));
            });
        });

        return formattedContent;
    } catch (error) {
        throw error;
    } finally {
        await Promise.all([
            new Promise((resolve) => {
                fs.unlink(tempFilePath, (err) => {
                    if (err) {
                        console.error(`Failed to delete temporary file '${tempFilePath}': ${err.message}`);
                    }
                    resolve();
                });
            }),
            deleteFilesMatchingPattern(/~$/)
        ]);
    }
};
```

**Comment by Delgan** [comment] 2024-12-02 09:36
Hi @m-diers.

Which version of Qt are you using?

There was a bug with Qt 6.4, see this comment: https://github.com/Delgan/qml-format/issues/5#issuecomment-1537093867

**Comment by m-diers** [comment] 2024-12-02 10:57
Hi @Delgan 
Yes, version is `Using Qt version 6.4.2 in /usr/lib/x86_64-linux-gnu`.
FYI: This is the default version of ubuntu 24.04 lts.
Therefore, the issue can be closed from my side.

**Comment by Delgan** [comment] 2024-12-02 13:09
Ok, thanks for the info. I advise you to update Qt if possible.

I'm closing this ticket since this is an upstream bug and not a bug within this extension.

I could eventually accept a PR if someone wants to implement a workaround in this extension.

**Closed as completed by Delgan** 2024-12-02 13:09 UTC
Labels: duplicate
