### ISSUE TITLE
New temporary file is created

### ISSUE THREAD

**Issue by dbalints** [Delgan/qml-format#5] opened 2023-02-01 10:07 UTC
For each formatting I do in QML files, a new temporary file gets created with a filename pattern of: {filename}-{somehash}-formatting-tmp.qml

I use Qt 6.2.6

**Comment by dbalints** [comment] 2023-02-01 10:15
I just looked in the code, maybe it is because I do not have Admin rights in the Windows computer I'm using?

**Comment by Delgan** [comment] 2023-02-01 20:44
Hi @dbalints.

The implementation of `qml-format` intentionally creates a temporary file, as you understood. This is required so that the `qmlformat` external command can be properly executed on the file and the result sent back to VS Code. 

However, once the formatting succeeded, the temporary file is supposed to be removed. Does the file persist in your case? If this is not the case, an error is usually displayed in VS Code.

**Comment by dbalints** [comment] 2023-02-05 19:17
> Hi @dbalints.
> 
> The implementation of `qml-format` intentionally creates a temporary file, as you understood. This is required so that the `qmlformat` external command can be properly executed on the file and the result sent back to VS Code.
> 
> However, once the formatting succeeded, the temporary file is supposed to be removed. Does the file persist in your case? If this is not the case, an error is usually displayed in VS Code.

Hello @Delgan 
Yes! The file persists in my case.

**Comment by Delgan** [comment] 2023-02-15 10:33
I'm sorry @dbalints, I don't know what could be the problem. I can't reproduce it. I'm afraid you're on your own in this case, if you want to investigate further. :(

Is your project located in a path were creating and deleting files requires admin rights?
Are you able to manually delete the file ?
Are you sure there is no error message reported in VS Code (there should be a windows opened and referencing the problem)?

**Comment by centercao** [comment] 2023-04-14 05:09
me too.so many I can delete by manual

**Comment by Delgan** [comment] 2023-04-14 09:35
@centercao Can you please give more details about your configuration (OS, Qt version, VS Code setup, etc.) please?

Also, can you confirm that there is no error message displayed by VS Code while formatting the file?

**Comment by dirkolbrich** [comment] 2023-05-03 12:43
I experience the same problems of persistent temp files, sometimes multiple for the same base file, as with each format a new temp file is created.

This file is created on a successful format operation, e.g. I have a valid .qml file and delete a line like `anchors.fill: parent` but leave the empty line in place. The format operation deletes this empty line, but creates a new persistent temp file in the same folder as the base source file.
An error in the file like `anchors.fill:` (without the parent definition) creates a pop-up window the the error message, but no temp file.

I'm using [VSCodium](https://vscodium.com) on macOS Ventura 13.3.1(a) on a Apple M1 Max:

Version: 1.77.3
Release: 23102
Commit: 650fc437e02159df39d99355a91b2e3b1f1220c5
Date: 2023-04-12T18:12:53.725Z
Electron: 19.1.9
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 22.4.0
Sandboxed: No

I'm using the latest QT version 6.4.3_3 installed via homebrew.

**Comment by dirkolbrich** [comment] 2023-05-03 12:59
I think the error is in (or after) this line:  https://github.com/Delgan/qml-format/blob/0c2d1aca964c72d42169c056e4478bda48681495/src/formatter.ts#L35

The temp file is written to disc, but never deleted after a successful return from the function.

The included line: https://github.com/Delgan/qml-format/blob/0c2d1aca964c72d42169c056e4478bda48681495/src/formatter.ts#L44

should delete the file according to the [Node.js docs](https://nodejs.org/dist/latest-v20.x/docs/api/fs.html#fspromisesunlinkpath): _If the path refers to a file path that is not a symbolic link, the file is deleted._, but fails to do so.

**Comment by Delgan** [comment] 2023-05-05 19:12
Thanks for the additional details @dirkolbrich.

It is interesting to note that the problem occurs on macOS and that the bug is not specific to Window. The behavior you observe seems to indicate that `unlink()` fails to delete the file but yet does not return an error.

Unfortunately, being unable to reproduce the problem, and despite my research, I have no idea how to explain this behavior.

If you have time, I can provide a NodeJS script that you should run to understand if the problem is related to VS Code or not.

**Comment by dirkolbrich** [comment] 2023-05-05 20:30
Sorry, I am a complete noob in JS programming and don't know anything about debugging Electron apps.

Just an idea though. Could it be that `fs.unlink()` deletes the temp file correctly, but as it returns via `fs.readFile()` (which still holds the temp file data) to `fs.writeFile()`, the temp file is rewritten again?

**Comment by Delgan** [comment] 2023-05-05 22:09
I would have just shared a script to run via the `node` command (if you managed to install it), and depending on the result, it could have directed us to the source of the problem. No need for debugging Electron app.
But no worries, it's ok. It's just that I can't help you any further unfortunately.


> Just an idea though. Could it be that `fs.unlink()` deletes the temp file correctly, but as it returns via `fs.readFile()` (which still holds the temp file data) to `fs.writeFile()`, the temp file is rewritten again?

Sorry, I'm not sure to understand. But I don't think it's possible for `fs.WriteFile()` to be called twice, it's just using callback.

**Comment by dirkolbrich** [comment] 2023-05-06 06:37
Well, let's give it a try. I have node installed. Please share the script (maybe via a gist) along with the steps to run it and I will give it a shot.

Another thought: As the persistent temp file ends in `.qml~` <- note the extra tilde character - maybe it is an artifact of the `qmlformat` child_process call?
A solution could be to add a cleanup function after `fs.writeFile()`. The formatting of the base file is done at this point, now check if the `.qml~` still exists and delete if necessary.

**Comment by Delgan** [comment] 2023-05-06 08:54
@dirkolbrich Oh, wait a minute, you say the file ends with `.qml~`? I thought the undeleted files you saw ended with `formatting-tmp.qml`.

The `.qml~` files are created by the `qmlformat` command.
The  `formatting-tmp.qml` files are created by this VS Code extension.

Actually, there was a bug on Windows with Qt 6.4.0 causing `.qml~` files not to be deleted: https://bugreports.qt.io/browse/QTBUG-107685
Maybe there is also a problem on macOS? 

> A solution could be to add a cleanup function after `fs.writeFile()`. The formatting of the base file is done at this point, now check if the `.qml~` still exists and delete if necessary.

That would be possible, indeed, although I would prefer not to.

Anyway, the first thing you can try is to manually run the `qmlformat`. Call `qmlformat` on one of the files of your project and let me know if it creates new undeleted files.

About the `node` script, here is what I had in mind:

```js
child_process = require('child_process');
fs = require('fs');
path = require('path');

const runQmlFormatter = async (command, args, fileContent, filePath) => {
    return new Promise((resolve, reject) => {

        if (!fileContent.trim()) {
            return resolve("");
        }

        const randomString = Math.random().toString(36).substring(2, 10);
        const pathObject = path.parse(filePath);
        const fileName = pathObject.base;
        // The file must ends with ".qml" otherwise "qmlformat" will output an error.
        const tempFilePath = path.join(pathObject.dir, `${pathObject.name}-${randomString}-formatting-tmp.qml`);


        fs.access(tempFilePath, fs.constants.F_OK, (err) => {
            if (!err) {
                return reject(`Formatting of '${fileName}' aborted because file '${tempFilePath}' already exists.`);
            }
            fs.writeFile(tempFilePath, fileContent, { "encoding": "utf8" }, (writeError) => {
                if (writeError) {
                    return reject(`Formatting of '${fileName}' aborted because file '${tempFilePath}' could not be created: '${writeError.message}'.`);
                }
                // We must format the file in-place and not rely on stdout.
                // For one thing, "\n" outputed by "qmlformat" would be transformed to "\r\n" on Windows, which causes problems with "NewlineType=windows" option.
                // Secondly, the "execFile" buffer size is limited (~1MB by default), so it's not reliable enough to use it.
                child_process.execFile(command, ["-i", tempFilePath].concat(args), (execError, _execStdout, _execStderr) => {
                    fs.readFile(tempFilePath, { "encoding": "utf8" }, (readError, readData) => {
                        fs.unlink(tempFilePath, (unlinkError) => {
                            // The "execStdout" and "execStderr" are ignored for now (because they should not cause a failure).
                            // It would probably be better to log them somehow.
                            if (execError) {
                                return reject(`Formatting of '${fileName}' failed (${execError.code}): '${execError.message}'.`);
                            }
                            if (readError) {
                                return reject(`Formatting of '${fileName}' aborted because file '${tempFilePath}' could not be read: '${readError.message}'.`);
                            }
                            if (unlinkError) {
                                return reject(`Formatting of '${fileName}' ended with an error because file '${tempFilePath}' could not be deleted: '${unlinkError.message}'.`);
                            }
                            return resolve(readData);
                        });
                    });

                });
            });
        });
    });
};

runQmlFormatter("qmlformat", [], "Text{}", "test.qml").then((result) => {
    console.log("OK:", result);
}).catch((error) => {
    console.error("NOK:", error);
});
```

You can copy/paste it into a `test.js` file and finally execute it with `node test.js`. Then let me know the output and whether it creates undeleted files.

**Comment by dirkolbrich** [comment] 2023-05-07 18:23
Sorry , I should have been more precise with my error reporting.

The persistent temp file has the ending `.qml~` and is indeed created by the `qmlformat` command. I was able to recreate the behavior by disabling your QML Format plugin and rerun the format on the cmd line with `qmlformat -i main.qml --verbose`. A `main.qml~` file is created and stays behind.

So this is an upstream bug of the `qmlformat` tool. The weird thing is, to the mentioned bug report under [QTBUG-107685 - qmlformat creates temp file with trailing "~" which is not removed](https://bugreports.qt.io/browse/QTBUG-107685) there is a commit [439245 - qmlformat: do not generate backup files](https://codereview.qt-project.org/c/qt/qtdeclarative/+/439245) attached, which should resolve the error.
This commit is part of my homebrew installed Qt osurce, I checked the source. But still the error persists.

**Comment by dirkolbrich** [comment] 2023-05-07 18:36
I reported the bug upstream under [QTBUG-113442](https://bugreports.qt.io/browse/QTBUG-113442).

**Comment by Delgan** [comment] 2023-05-07 18:42
@dirkolbrich Thanks for the update.

Is it possible that your `qmlformat` binary does not contain the patched version? Or that maybe there are two conflicting installations?

The fix was published in Qt 6.5.0.
I would assume it's a problem with `brew` more than Qt itself.

**Comment by dirkolbrich** [comment] 2023-05-08 11:06
Yes, this may be indeed the case.

The current Homebrew distributed Qt is at Version 6.4.3 and uses the source from https://download.qt.io/official_releases/qt/6.4/6.4.3/single/qt-everywhere-src-6.4.3.tar.xz. The update to the current Qt v6.5.x is currently stuck due to build issues, but hopefully will be resolved soon.

The patch for the persistent `*.qml~` temp file is in Qt v6.5.x and will be back ported to v6.2.x according to the comments to my opened issue at [QTBUG-113442](https://bugreports.qt.io/browse/QTBUG-113442), but not to v6.4.x 🥲.

So I guess I will have to sit this out.

**Comment by Delgan** [comment] 2023-05-08 16:58
Maybe there exists an extension you could use to automatically call `rm -rf *.qml~` but indeed, the most appropriate is surely to wait for a new release of Qt on homebrew, sorry. :grin:

**Comment by Delgan** [comment] 2023-05-08 17:13
@dbalints @centercao Do the undeleted files on your computer also end in `.qml~` (note the tilde)?

**Comment by dbalints** [comment] 2023-05-08 17:23
> @dbalints @centercao Do the undeleted files on your computer also end in `.qml~` (note the tilde)?

Yes! {fileName}-{randomStuff}-formatting-tmp.qml~

**Comment by Delgan** [comment] 2023-05-08 17:31
@dbalints Thanks!

So basically you have the answer: it's a bug in `qmlformat` command, you need to update to Qt 6.5.0 to get rid of these annoying files.

**Comment by Delgan** [comment] 2023-07-18 17:56
I'm closing the ticket as we agreed it's a problem due to the `qmlformat` version. :+1:

**Closed as completed by Delgan** 2023-07-18 17:56 UTC
